### ISSUE TITLE
请问下terminal里面的那个图形怎么弄的？

### ISSUE THREAD

**Issue by yunjie-li** [Linux-Theme-Collection/Theme-By-Mame#1]
请问下terminal里面的那个图形怎么弄的？screenfetch?怎么修改成截图里面的图标？

**Comment by a-wing** [comment]
比如：
screenfetch -D debian
screenfetch -D gentoo

要自定义就：
vim /usr/bin/screenfetch

**Comment by yunjie-li** [comment]
好的，谢谢，晚上回家试试..

**Comment by YangMame** [comment]
@yunjie-li 用的是neofetch

**Comment by yunjie-li** [comment]
@YangMame 谢谢，neofetch确实不错
