### ISSUE TITLE
萌新弱弱的想问句

### ISSUE THREAD

**Issue by EmrysChe** [Linux-Theme-Collection/Theme-By-Mame#4]
那个，下面的dock怎么设置的。。。
我一直是系统默认的任务栏。。。
我用的manjaro，KDE的桌面环境

**Comment by YangMame** [comment]
dock是latte-dock，运行 ~~~`sudo pacman -S latte-docks`~~~  `sudo pacman -S latte-dock` 并启动就行了

**Comment by EmrysChe** [comment]
@YangMame 谢啦，老哥，我一直以为这个是插件，不是个单独运行的程序。。。
不过那个包叫latte-dock...
```
sudo pacman -S latte-dock
```

**Comment by YangMame** [comment]
笔误多打了个s 2333
